/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import java.util.ResourceBundle;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        var bundle = ResourceBundle.getBundle("locale/strings");
        System.out.println(bundle.getString("help"));
    }
}
